services:
  - type: web
    name: campus-recruitment-system
    env: python
    buildCommand: ""
    startCommand: gunicorn campus_runner.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: campus_runner.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: campus-db
          property: connectionString

databases:
  - name: campus-db
    databaseName: campusdb
    user: campususer
