# Generated by Django 5.1.7 on 2025-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_activitylog_user_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unnamed Student', max_length=255),
            preserve_default=False,
        ),
    ]
